version: "3.3"

services:
  identidock:
    build: .
    container_name: testapp
    ports:
      - "5000:5000"
    environment:
      ENV: DEV
    volumes:
      - ./app:/app
    links:
      - dnmonster
      - redis

  dnmonster:
    image: amouat/dnmonster:1.0
    container_name: testpic

  redis:
    image: redis:latest
    container_name: testcache
